version: '3.7'

services:
  db:
    container_name: db
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: flask
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: chat

  wait_db:
    container_name: wait_db
    image: busybox:1.28
    command: sh -c 'while ! nc -z -v -w 3 db 3306; do sleep 5; done'

  app:
    container_name: app
    image: ${REPO}
    depends_on:
    - wait_db

  wait_app:
    container_name: wait_app
    image: busybox:1.28
    command: sh -c 'while ! nc -z -v -w 3 app 5000; do sleep 5; done'

  proxy:
    container_name: proxy
    image: nginx:alpine
    depends_on:
    - wait_app
    ports:
    - "${PORT}:80"
    volumes:
      - jenkins_home:/var/jenkins_home
      #- ./web/static:/usr/share/nginx/html
      #- ./nginx:/etc/nginx/nginx.conf
    command: >
      sh -c "rm -rf /etc/nginx/nginx.conf  &&
             echo '1' && rm -rf /usr/share/nginx/html &&
             echo '2' &&
             ln -s ${WORKSPACE}/nginx/nginx.conf /etc/nginx/nginx.conf &&
             echo '3' &&
             ln -s ${WORKSPACE}/web/static /usr/share/nginx/html &&
             echo '4' &&
             exec /docker-entrypoint.sh nginx -g 'daemon off;' && echo '5'"

volumes:
  jenkins_home:
    external: true
