version: '3.7'

services:
  db:
    container_name: db
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: flask
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: chat

  wait_db:
    container_name: wait_db
    image: busybox:1.28
    command: sh -c 'while ! nc -z -v -w 3 db 3306; do sleep 5; done'

  app:
    build:
      dockerfile: chat.Dockerfile
      context: .
    container_name: app
    image: app:0.1
    depends_on:
    - wait_db

  wait_app:
    container_name: wait_app
    image: busybox:1.28
    command: sh -c 'while ! nc -z -v -w 3 app 5000; do sleep 5; done'

  proxy:
    container_name: proxy
    image: nginx:alpine
    depends_on:
    - wait_app
    ports:
    - "80:80"
    volumes:
    - ./web/static:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
